### ISSUE TITLE
Bug in BuildHelper.getBefore?

### ISSUE THREAD

**Issue by fermadeiral** [Spirals-Team/jtravis#21]
When obtaining a build with the method `BuildHelper.getBefore()` like this:

`Optional<Build> optionalBeforeBuild = jTravis.build().getBefore(build, true);`

All `Optional<Log>` returned with `job.getLog()` from the build in `optionalBeforeBuild` are `Optional.empty`:

```
if (optionalBeforeBuild.isPresent()) {
   Build previousBuild = optionalBeforeBuild.get();
   for (Job job : previousBuild.getJobs()) {
      jTravis.refresh(job);
      if (job.getState() == StateType.FAILED) {
         Optional<Log> optionalLog = job.getLog();
         if (optionalLog.isPresent()) {
            ...
         } else {
            // the code here is executed
         }
      }
   }
}
```

And the job logs should be present.

To make it work for the moment:

```
Build previousBuild = optionalBeforeBuild.get();
previousBuild = jTravis.build().getEntityFromUri(Build.class, previousBuild.getUri()).get(); // to add this line
```

For reproduction of the bug: `BuildHelper.getBefore()` should be called from build 324525330 (INRIA/spoon), and the job logs will not be present for the before build returned.

**Comment by surli** [comment]
@fermadeiral I tried to reproduce the bug in a test that I pushed in the PR, but as you can see apparently the test is passing fine. Are you sure your bug is not related with a token issue?

**Comment by fermadeiral** [comment]
> @fermadeiral I tried to reproduce the bug in a test that I pushed in the PR, but as you can see apparently the test is passing fine.

=/

> Are you sure your bug is not related with a token issue?

I'm almost sure, because I broke and fixed the build from repairnator in Travis because of this, i.e. I have a failing and a passing situation in Travis with no change in token config (no environment change).

I saw your test and it seems ok (i.e. it should expose the issue I had yesterday). I will think about it. I will close this issue soon if I find nothing to show you the problem.

**Comment by fermadeiral** [comment]
> Are you sure your bug is not related with a token issue?

I started to think that yes, it is a token issue, but I believe this is possible to be from inside jTravis. I translated your test in a normal java code (i.e. without assertions), and the job logs are still not present. So one guess I have now is that somewhere "jtravis" or the token is changed inside jtravis in the middle of the execution of the method `BuildHelper.getBefore`. This could explain why with my token it is not working, and why a test from inside jtravis (your PR) this works. Unfortunately, I can't show you a proof of the existence of the problem, but a way for you to confirm and see by yourself on what I'm talking about, it's to do like a did: to call jtravis from outside jtravis, and to observe if the job logs are present or not.

**Comment by fermadeiral** [comment]
> Sorry but I don't really have time to do the check you suggest.

It's ok Simon, I understand.

> Anyway, if the problem doesn't happen again I would close this issue.

I will close this issue. This issue disappeared in Repairnator after I did the workaround I described in my first comment in this issue, thus the things are working there anyways.
